name: Lint Actions Demo
on: [push]
jobs:
  start_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - run: |
         sudo apt install pip
         pip install black
      

